app:
  description: ''
  icon: ğŸ¤–
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: RAG-Entry
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/openai_api_compatible:0.0.19@219552f62b54919d6fd317c737956d3b2cc97719b85f0179bb995e5a512b7ebb
kind: app
version: 0.3.1
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ä½ å¥½ï¼Œæˆ‘æ˜¯ä¸€ä¸ªçŸ¥è¯†åº“åŠ©æ‰‹ï¼Œè¯·é—®æˆ‘å…³äºè¯¥çŸ¥è¯†åº“çš„ä»»ä½•é—®é¢˜ï¼Œæˆ‘å°†ä¸ºæ‚¨åšä¸“ä¸šçš„å›ç­”ã€‚
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions:
    - é€‰ç…¤å‚é‡‡å–äººå·¥æ‰‹é€‰æ—¶å€™åº”ç¬¦åˆå“ªäº›è§„å®š
    - çŸ¿å±±æœºæ¢°ç£¨æŸå¤±æ•ˆåŸå› 
    suggested_questions_after_answer:
      enabled: true
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: knowledge-retrieval
        targetType: if-else
      id: 1749781548761-source-1749781561585-target
      selected: false
      source: '1749781548761'
      sourceHandle: source
      target: '1749781561585'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: if-else
        targetType: answer
      id: 1749781561585-true-1749781564025-target
      selected: false
      source: '1749781561585'
      sourceHandle: 'true'
      target: '1749781564025'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: llm
        targetType: answer
      id: 1749781705977-source-1749781731563-target
      selected: false
      source: '1749781705977'
      sourceHandle: source
      target: '1749781731563'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: llm
        targetType: answer
      id: 1749781705977-fail-branch-1749781739390-target
      selected: false
      source: '1749781705977'
      sourceHandle: fail-branch
      target: '1749781739390'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: code
      id: 1749779660144-source-1751512178242-target
      source: '1749779660144'
      sourceHandle: source
      target: '1751512178242'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: code
        targetType: if-else
      id: 1751512178242-source-1751512201471-target
      source: '1751512178242'
      sourceHandle: source
      target: '1751512201471'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: if-else
        targetType: answer
      id: 1751512201471-true-1751512231379-target
      source: '1751512201471'
      sourceHandle: 'true'
      target: '1751512231379'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: if-else
        targetType: llm
      id: 1749781561585-false-1749781705977-target
      source: '1749781561585'
      sourceHandle: 'false'
      target: '1749781705977'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: if-else
        targetType: knowledge-retrieval
      id: 1751512201471-false-1749781548761-target
      source: '1751512201471'
      sourceHandle: 'false'
      target: '1749781548761'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: å¼€å§‹
        type: start
        variables: []
      height: 54
      id: '1749779660144'
      position:
        x: 1058.7187433132515
        y: 13.915876474917937
      positionAbsolute:
        x: 1058.7187433132515
        y: 13.915876474917937
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        dataset_ids:
        - a2LQI0bJ9YvEZ6pNrL54ET94tnshdIFCB2plMZck00TOq3tzQP3I0Bk+c8EyH5Ii
        desc: ''
        multiple_retrieval_config:
          reranking_enable: false
          reranking_mode: weighted_score
          reranking_model:
            model: qwen3-reranker
            provider: langgenius/openai_api_compatible/openai_api_compatible
          score_threshold: 0.4
          top_k: 5
          weights:
            keyword_setting:
              keyword_weight: 0
            vector_setting:
              embedding_model_name: bge-m3
              embedding_provider_name: langgenius/openai_api_compatible/openai_api_compatible
              vector_weight: 1
        query_variable_selector:
        - sys
        - query
        retrieval_mode: multiple
        selected: false
        title: çŸ¥è¯†æ£€ç´¢
        type: knowledge-retrieval
      height: 92
      id: '1749781548761'
      position:
        x: 2246.8876547665154
        y: 311.55786843598605
      positionAbsolute:
        x: 2246.8876547665154
        y: 311.55786843598605
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: empty
            id: 180b11b3-9155-4f57-88be-ec36a97d7f30
            value: ''
            varType: array[object]
            variable_selector:
            - '1749781548761'
            - result
          id: 'true'
          logical_operator: and
        desc: ''
        selected: false
        title: æ¡ä»¶åˆ†æ”¯
        type: if-else
      height: 126
      id: '1749781561585'
      position:
        x: 2613.153205534946
        y: 311.55786843598605
      positionAbsolute:
        x: 2613.153205534946
        y: 311.55786843598605
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: éå¸¸æŠ±æ­‰ï¼ŒæŸ¥è¯¢çš„å…³äºâ€œ{{#sys.query#}}â€ è¿™ä¸ªé—®é¢˜ï¼Œåœ¨æˆ‘ä»¬çš„çŸ¥è¯†åº“é‡Œé¢æ²¡æœ‰æ‰¾åˆ°ï¼Œæ‚¨å¯ä»¥é—®æˆ‘çŸ¥è¯†åº“æƒ³è¦äº†è§£çš„é—®é¢˜ï¼Œæˆ‘ä¼šå°½é‡ä¸ºæ‚¨åšå‡ºè¯¦å°½è§£ç­”ã€‚
        desc: ''
        selected: false
        title: ç›´æ¥å›å¤ 2
        type: answer
        variables: []
      height: 169
      id: '1749781564025'
      position:
        x: 3134.9696858662264
        y: 80.22393004719765
      positionAbsolute:
        x: 3134.9696858662264
        y: 80.22393004719765
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - '1749781548761'
          - result
        desc: ''
        error_strategy: fail-branch
        memory:
          query_prompt_template: '{{#sys.query#}}'
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: true
            size: 10
        model:
          completion_params: {}
          mode: chat
          name: Qwen3-30B-A3B
          provider: langgenius/openai_api_compatible/openai_api_compatible
        prompt_template:
        - id: e9862634-24ad-48ba-a57a-fa165d7d665d
          role: system
          text: ä½ æ˜¯ä¸€ä¸ªä¹äºåŠ©äººçš„åŠ©æ‰‹ï¼Œä¸“æ³¨äºçŸ¥è¯†åº“ç›¸å…³é—®é¢˜çš„è§£ç­”ä¸æ”¯æŒã€‚é¢å¯¹ç”¨æˆ·å’¨è¯¢æ—¶ï¼Œå¯¹ç”¨æˆ·é—®é¢˜ç»“åˆçŸ¥è¯†åº“çš„ä¸Šä¸‹æ–‡ï¼š{{#context#}},
            æ¥ç”Ÿæˆé€»è¾‘æ¸…æ™°ã€å†…å®¹è¯¦å®ã€ä¸“ä¸šå‡†ç¡®çš„å›ç­”ï¼Œä¸è¦è¿›è¡Œé¢å¤–æ¨æµ‹æˆ–è”æƒ³ã€‚
        - id: f7c2d1b2-fa45-486c-a8fb-4cebfac9e332
          role: user
          text: '{{#sys.query#}}'
        retry_config:
          max_retries: 3
          retry_enabled: true
          retry_interval: 1000
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 156
      id: '1749781705977'
      position:
        x: 3118.0721646723373
        y: 517
      positionAbsolute:
        x: 3118.0721646723373
        y: 517
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#1749781705977.text#}}'
        desc: ''
        selected: false
        title: ç›´æ¥å›å¤ 3
        type: answer
        variables: []
      height: 105
      id: '1749781731563'
      position:
        x: 3569.086287231571
        y: 291.1558349723
      positionAbsolute:
        x: 3569.086287231571
        y: 291.1558349723
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: å¤§æ¨¡å‹æœåŠ¡å¼‚å¸¸ï¼Œè¯·æŸ¥çœ‹æ—¥å¿—ï¼
        desc: ''
        selected: false
        title: ç›´æ¥å›å¤ 4
        type: answer
        variables: []
      height: 102
      id: '1749781739390'
      position:
        x: 3563.4268278593036
        y: 774.4523904512033
      positionAbsolute:
        x: 3563.4268278593036
        y: 774.4523904512033
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "import re \n\ndef main(arg1: str) -> dict:\n    if re.match(\"ä½ å¥½\"\
          , arg1) or re.match(\"ä½ æ˜¯è°\", arg1) or re.match(\"how are you\", arg1) or\
          \ arg1 == \"ä½ \":\n        return {\n            \"result\": \"True\",\n\
          \        }\n    else:\n        return {\n            \"result\": \"False\"\
          ,\n        }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: é—®å€™è¯­åˆ¤æ–­
        type: code
        variables:
        - value_selector:
          - sys
          - query
          variable: arg1
      height: 54
      id: '1751512178242'
      position:
        x: 1448.8009513772317
        y: 13.915876474917937
      positionAbsolute:
        x: 1448.8009513772317
        y: 13.915876474917937
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: is
            id: 26e117d9-e132-4101-9ad7-ee889e53448d
            value: 'True'
            varType: string
            variable_selector:
            - '1751512178242'
            - result
          id: 'true'
          logical_operator: and
        desc: ''
        selected: false
        title: æ¡ä»¶åˆ†æ”¯ 5
        type: if-else
      height: 126
      id: '1751512201471'
      position:
        x: 1842.4668902771216
        y: 13.915876474917937
      positionAbsolute:
        x: 1842.4668902771216
        y: 13.915876474917937
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: ä½ å¥½ï¼Œæˆ‘æ˜¯AIå°åŠ©æ‰‹ï¼Œæ‚¨å¯ä»¥é—®æˆ‘ç…¤çŸ¿ç›¸å…³é—®é¢˜ï¼Œæˆ‘ä¼šå°½é‡ä¸ºæ‚¨åšå‡ºè¯¦å°½è§£ç­”ã€‚
        desc: ''
        selected: false
        title: ç›´æ¥å›å¤
        type: answer
        variables: []
      height: 134
      id: '1751512231379'
      position:
        x: 2246.8876547665154
        y: -261.5608553459339
      positionAbsolute:
        x: 2246.8876547665154
        y: -261.5608553459339
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -1714.2495799359276
      y: 456.0116873710656
      zoom: 1.0111520808513068
